config/routes.rb
Brewsion::Application.routes.draw do  
  
  resources :plays do
    member do
      get :editkillcode
      put :updatekillcode
      post :updatekillcode
      get :edittargetkillcode
      put :updatetargetkillcode
      post :updatetargetkillcode
    end
  end

  resources :games do
    member do
      put :begingame
    end
  end

  devise_for :users
  resources :users, only: [:index]

  root :to => 'pages#home'
  get 'about' => 'pages#about'

end

app/models/game.rb
class Game < ActiveRecord::Base
  attr_accessible :gamename, :start, :end, :status, :description
  validates :gamename, presence: true
  validates :gamename, uniqueness: { case_sensitive: false }
  has_many :plays, class_name: "Play", foreign_key: "game_id", :dependent => :destroy
  
  # Adds Users to Games (after adding user_id column to Games and indexing user_id col in Games)
  belongs_to :user
  validates :user_id, presence: true

  validates_presence_of :start, :end, :status, :description

end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_filter :authenticate_user!, except: [:index]
  # GET /games
  # GET /games.json
  def index
    @games = Game.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @games }
    end
  end

  # GET /games/1
  # GET /games/1.json
  def show
    # @target_kill_code = params[:target_kill_code]
    @game = Game.find(params[:id])
    # This will let me display the plays for each game, in Show view
    @plays = @game.plays.all
    @play_as_assassin = @game.plays.where('userone_id' => current_user).first
    @play_as_target = @game.plays.where('targetuser_id' => current_user).first

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @game }
    end
  end

  # Here's the code to begin game, executed on click, to actually edit the table
  def begingame
    @game = Game.find(params[:id])
    # This will let me display the plays for each game, in Show view
    @plays = @game.plays.all
    # This is where my code for saving the shuffled targets begins
    shuffled = @game.plays.pluck(:userone_id).shuffle
    hash = Hash[shuffled.map.with_index.to_a]
    @plays.each { |n| n.update_attribute(:targetuser_id, shuffled[hash[n.userone_id]-1]) }
    # Change the status of this game to "1," which means "started"
    @game.update_attribute(:status, 1)
    # Upon clicking "Begin Game," redirect to game's show screen
    # and pass a notice that the game was succeffully started.
    respond_to do |format|
      format.html { redirect_to @game, notice: 'Game was successfully started.'  }
      format.json { head :no_content }
    end

  end

  # I removed the old getnewtarget from here

  # GET /games/new
  # GET /games/new.json
  def new
    # @game = Game.new
    @game = current_user.games.new
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @game }
    end
  end

  # GET /games/1/edit
  def edit
    # @game = Game.find(params[:id])
    @game = current_user.games.find(params[:id])
  end

  # POST /games
  # POST /games.json
  def create
    # @game = Game.new(params[:game])
    @game = current_user.games.new(params[:game])

    respond_to do |format|
      if @game.save
        format.html { redirect_to @game, notice: 'Game was successfully created.' }
        format.json { render json: @game, status: :created, location: @game }
      else
        format.html { render action: "new" }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /games/1
  # PUT /games/1.json
  def update
    # @game = Game.find(params[:id])
    @game = current_user.games.find(params[:id])

    respond_to do |format|
      if @game.update_attributes(params[:game])
        format.html { redirect_to @game, notice: 'Game was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1
  # DELETE /games/1.json
  def destroy
    # @game = Game.find(params[:id])
    @game = current_user.games.find(params[:id])
    @game.destroy

    respond_to do |format|
      format.html { redirect_to games_url }
      format.json { head :no_content }
    end
  end



end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/_form.html.erb
<%= simple_form_for(@game) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :gamename %>
    <%= f.input :start %>
    <%= f.input :end %>
    <%= f.input :description %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/games/_gamestats.html.erb
<h1>Game Stats for <%= @game.gamename %></h1>

<div>

  <div id="stats_target">


    <h2>Your Target</h2>
    
    <div id="target_pic">
      <p>Picture placeholder</p>
    </div>

    <div id="target_info">
      <p>Username: <%= @play_as_assassin.target.try(:username) %></p>
      <p>First Name: <%= @play_as_assassin.target.try(:firstname) %></p>
      <p>Last Name: <%= @play_as_assassin.target.try(:lastname) %></p>
      <p>Email: <%= @play_as_assassin.target.try(:email) %></p>
      <p>Maybe link to more information about the target? (Based on selections by the game creator?)</p>
    </div>

  </div>

  <div id="stats_you">

    <h2>You</h2>
    <p>Username: <%= @play_as_assassin.assassin.try(:username) %></p>
    <% if @play_as_assassin.try(:kills) != nil %>      
      <p>Number of Kills: <%= @play_as_assassin.try(:kills) %></p>
    <% end %>
    <p>Kill Code: <%= @play_as_target.try(:useronekillcode) %></p>
    <p><%= link_to 'Edit my Kill Code', editkillcode_play_path(@play_as_assassin) %></p>
    <p><%= link_to 'Edit my User Info', edit_user_registration_path %></p>

  </div>

</div>

<div id="next_target">
  <p><%= link_to 'Get New Target', edittargetkillcode_play_path(@play_as_assassin) %></p>
</div>

<div id="stats_game">

  <h2>The Game</h2>
  <p>Placeholder for number of people playing and number of people killed</p>
</div>

app/views/games/begin.html.erb
<%= # Added this, but it's not working as hoped. Probably delete. %>
<h1>Listing plays for this game</h1>

<table>
  <tr>
    <th>Game ID</th>
    <th>Game Name</th>
    <th>UserOne ID</th>
    <th>UserOne Name</th>
    <th>TargetUser ID</th>
    <th>TargetUser Name</th>
    <th>UserOne Kill Code</th>
  </tr>

<% @plays.each do |play| %>
  <tr>
    <td><%= play.game_id %></td>
    <td><%= play.game.gamename %></td>
    <td><%= play.userone_id %></td>
    <td><%= play.user.username %></td>
    <td><%= play.targetuser_id %></td>
    <td><%= play.targetuser_id %></td>
    <td><%= play.useronekillcode %></td>
    <td><%= link_to 'Show', game %></td>
    <% if current_user == game.user %>
      <td><%= link_to 'Begin', begin_game(game) %></td>
      <td><%= link_to 'Edit', edit_game_path(game) %></td>
      <td><%= link_to 'Destroy', game, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    <% end %>
  </tr>
<% end %>
</table>

<br />

<% if current_user == @game.user %>
	<%= link_to 'Edit', edit_game_path(@game) %> |
<% end %>
<%= link_to 'Back', games_path %>

app/views/games/edit.html.erb
<h1>Editing game</h1>

<%= render 'form' %>

<%= link_to 'Show', @game %> |
<%= link_to 'Back', games_path %>

app/views/games/index.html.erb
<h1>Listing games</h1>

<table>
  <tr>
    <th>Game ID</th>
    <th>User ID</th>
    <th>Creator user name</th>
    <th>Game name</th>
    <th>Start</th>
    <th>End</th>
    <th>Status</th>
    <th>Description</th>
  </tr>

<% @games.each do |game| %>
  <tr>
    <td><%= game.id %></td>
    <td><%= game.user_id %></td>
    <td><%= game.user.username %></td>
    <td><%= game.gamename %></td>
    <td><%= game.start %></td>
    <td><%= game.end %></td>
    <td><%= game.status %></td>
    <td><%= game.description %></td>
    <td><%= link_to 'Show', game %></td>
    <% if current_user == game.user %>
      <td><%= link_to 'Edit', edit_game_path(game) %></td>
      <td><%= link_to 'Destroy', game, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    <% end %>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Game', new_game_path %>

app/views/games/new.html.erb
<h1>New game</h1>

<%= render 'form' %>

<%= link_to 'Back', games_path %>

app/views/games/show.html.erb
<!--If this Game has begun, the gamestats will be rendered below-->
<% if @game.status == 1 %>
  <%= render 'gamestats' %>
<% end %>

<!--Begin temporary listing of Plays for this Game-->

<p style="color:red">This red section will be deleted before Go-Live</p>
<h1 style="color:red">Listing plays for this game</h1>

<table style="color:red">
  <tr>
    <th>Game ID</th>
    <th>Game Name</th>
    <th>Play ID</th>
    <th>UserOne ID</th>
    <th>UserOne Name</th>
    <th>TargetUser ID</th>
    <th>TargetUser Name</th>
    <th>UserOne Kill Code</th>
    <th>UserOne Kills</th>
    <th>Target Kill Code (NEW)</th>
  </tr>

<% @plays.each do |play| %>
  <tr>
    <td><%= play.game_id %></td>
    <td><%= play.game.gamename %></td>
    <td><%= play.id %></td>
    <td><%= play.assassin.id %></td>
    <td><%= play.assassin.username %></td>
    <td><%= play.target.try(:id) %></td>
    <td><%= play.target.try(:username) %></td>
    <td><%= play.useronekillcode %></td>
    <td><%= play.kills %></td>
    <td><%= play.try(:targetkillcode) %></td>
  </tr>
<% end %>
</table>

<!--End temporary listing of Plays for this Game-->

<% if @game.status == 0 %>
  <%= link_to 'Begin Game', { action: "begingame", id: @game }, method: :put %> |
<% end %>

<% if current_user == @game.user %>
	<%= link_to 'Edit', edit_game_path(@game) %> |
<% end %>
<%= link_to 'Back', games_path %>